### PR TITLE
Improve introduction vignette

### PR DESCRIPTION
**Pull request by llrs**
Updating the introduction vignette
Keeping in mind the users and other material as reported on #624

### CODE REVIEW

**Comment by llrs** [comment]
Hi @PythonCoderUnicorn, @resulumit I worked on the introduction vignette (rtweet.Rmd) . As someone who teach how to use the package do you think it shows a complete picture of the package? Would you include something more or explain different something?

**Comment by PythonCoderUnicorn** [comment]
Hi llrs &  @resulumit 

I checked the README and think it is good. At the top after how to install the package you have information on needing the API keys/ authentication which is necessary to know. 

The code snippets are good. 

 As to your query "does this show the full picture of the package?" I do not think so. The README is good at getting going but you would need a revised rtweet pdf documentation (based on my last read for my initial understanding and use for making my learnr file guide). In this guide is where I would be more expressive/ explicit with examples.  Main point is that Twitter API is powerful and can grab so much data, the use-case rationale for using grab favorites (likes) would be an example to put next to code snippet (or elsewhere). 

**If interested** I made my own [rtweet guide](https://rtweetguide.netlify.app/) (revised leanr file i posted an issue months ago) which helps user with most of the functions.  I have a RLadies slide on how to use this package as well (2 full demos), link [here](https://pythoncoderunicorn.github.io/rtweet-tutorial/#1)

thanks for tagging me. : )

**Comment by llrs** [comment]
Many thanks for giving feedback so quick. However, I don't fully understand your third paragraph: The pdf documentation documentation is generated by CRAN, or you can generate it via `tools`. Which is "this guide" you are referring to on the third sentence? The README or the rtweet vignette? 

note to self: Address #605

**Comment by PythonCoderUnicorn** [comment]
The rtweet documentation pdf is the *guide* I am referring to. I did not know it was generated by CRAN. 
If you would like some of my help on the documentation for the pdf guide I would be happy to contribute. 

Sentences 1 and 2 are about the README part.  

Hope things are clear. : )

**Comment by llrs** [comment]
Tidying the issues: I think I removed the mentions to internal functions in the documentation, which should close #537

**Pull request merged**
