### PR TITLE
Adding blocking and unblocking

### PR DESCRIPTION
**Pull request by simonheb**
I was missing blocking and unblocking functionality.

Since muting was inside `post_follow`, I added blocking (and unblocking) to the same file. It's tested and worked for me.

### CODE REVIEW

**Comment by llrs** [comment]
Thanks! Not sure about adding new features with API v1, but it will be useful as a reminder. Could you add a test (add some existing "random" user). The code change seems minimal and without major issues (I think you need to document again the package though, as it fails on the CI checks due to this).

**Comment by hadley** [comment]
I'm uncertain if its a good idea to continue to add even more features to this already large function. Maybe it would be better to have new functions?

**Comment by llrs** [comment]
Yes, I had drafted a comment myself regarding this. However, I also hesitate to create new functions until #572 isn't merged and renaming all functions following previous discussions (I don't find the issue/PR were we discussed this now).

**Comment by simonheb** [comment]
not sure I understand the comment about v1? what is your preferred way to deal with functionally that does not yet exist?

I appreciate the feedback about not bloating this one function. Since I do not know what the general plans are regarding the overall structure I will not push for further additions.

**Comment by simonheb** [comment]
I've added the tests and documented it. Should work now.

**Comment by llrs** [comment]
There is a new [API v2](https://developer.twitter.com/en/docs/twitter-api/early-access ), currently rtweet is using [API v1](https://developer.twitter.com/en/docs/twitter-api/v1). There are many differences between the way to call data, the endpoints and the data returned. 

Currently my efforts are to set up the package in better shape for adding support for API v2 as Twitter is clearly moving to use and update only API v2. I don't know how long it will take but API v1 will at some point be deprecated (years probably). Adding features is great, specially if they require few time and checks on my side. But this is also depends on how are they implemented and in relation to other functions. Just don't add features because they are cool but because you use them (or want to use them) and we'll find a way to get them included. 

On this particular case it is true that post_follow is already doing many different so I think it is better to move it to its own function `block_user(user, unblock = FALSE)`.

**Comment by simonheb** [comment]
But afaik the API v2 is not yet accessible outside of the early access program. Or am I misinterpreting this?

Yes, I implemented the blocking because I needed it for my app. I will move this into a new function like you suggested.

**Comment by llrs** [comment]
The early access program is quite open to developers and lately they are doing events and explaining how to work with [academictwitteR](https://cran.r-project.org/package=academictwitteR). 
The package received a comment from one of the developers of Twitter around a year ago (see #402), so it is acceptable to provide support and move to the new API.

**Comment by simonheb** [comment]
Ok, interesting. I've been fiddling around with some code (e.g. to add support for fetching alt-text/captions for tweets with images, as I am using `rtweet` to run the bot [@CaptionClerk](http://twitter.com/CaptionClerk)). I was considering merging this functionality into `rtweet`, but maybe it's better if I wait until this has moved to the v2. I could also try to help with this, just give me a hint on where to start.

**Comment by llrs** [comment]
@simonheb Maybe you can tackle #566 (I had a PR on the wrong direction #567)

**Comment by hadley** [comment]
Should these be `user_block()` and `user_unblock()`? Or `block_user()` and `unblock_user()`?

**Comment by simonheb** [comment]
I agree that `block_user()` and `unblock_user()` are more intuitive. Will change this.

**Comment by llrs** [comment]
About the naming convention we discussed this on #480. I think `user_block()` and `user_unblock()` makes more sense and it is following the first suggestion from [this comment](https://github.com/ropensci/rtweet/issues/480#issuecomment-791421334) and the first suggestion from Hadley (sorry you need to rename this functions again).

**Comment by simonheb** [comment]
ok no worries, fair point. I was not aware of #480. would it additionally make sense to rename the file `post-block.r` to something else?

**Comment by llrs** [comment]
Oh, I hadn't tough about renaming files, probably it would be nice to have matching files (so user-block.R). But don't worry if you don't, soon I'll start a new PR to rename all functions and then I'll see if renaming files makes sense.

**Comment by ronnicolasp** [comment]
Please allow me to join in! Can I contribute?

**Comment by llrs** [comment]
Hi @ronnicolasp, what do you want to join? What do you want to contribute?

**Comment by llrs** [comment]
I updated the PR with recent changes, added some tests and changed the user on the examples.
I'm still not decided about the names, the point on #480 about tab completion is compelling (`user_block`, `user_block_destroy`) but at the same time I wish it felt more natural to the users (`user_block`, `user_unblock`).

**Pull request merged**
