### PR TITLE
Drastically simplify rate_limit()

### PR DESCRIPTION
**Pull request by hadley**
* [x] Default rate limit error needs to give more details; should give limits and time needed to wait
* [x] In paginated functions, hitting a rate limit should terminate early with a warning, but still return all data retrieved so far
* [x] Optionally (and with global option) should be able to opt-in to instead waiting

### CODE REVIEW

**Comment by hadley** [comment]
@llrs you don't need to read the code, but I'd appreciate you trying out the user experience with `search_tweets()` and `get_followers()`. The documentation and messaging should make it clear what's going on, so please let me know if you have any confusion.

I need to stop working on rtweet and get back to Mastering Shiny, so the pace of contributions should be much slower this week.

**Comment by llrs** [comment]
Not sure it is working, I tried `rate_limit("/lists/list")` but it failed when trying to initialize an empty tibble: Error: Input must be a vector, not NULL.
From the user experience, previously one could use `rate_limit("lookup_users")` and it would use the right endpoint. But that can be added later.

Also I tried `st <- search_tweets("#rstats", n = 1000, retryonratelimit = TRUE)` to see what would happen and got a:
> Rate limit exceeded for Twitter endpoint 'search/tweets' . Waiting for refresh in  X mins /


So from other functions seems to work well, not sure the user needs to know endpoint perhaps it could be shortened to 

> Rate limit exceeded. Waiting for refresh in X mins.

**Comment by llrs** [comment]
Many thanks for all the heavy lifting so far! 
I will look at the other issues left and slowly work on them.

**Comment by hadley** [comment]
Good catch, I fixed that.  Note that #510 tracks the application of these principles to every function.

**Review by llrs — COMMENTED** [review]
LGTM

**Pull request merged**
