### PR TITLE
add functions for tweet embedding and threading

### PR DESCRIPTION
**Pull request by yonicd**

### CODE REVIEW

**Comment by yonicd** [comment]
the threading function needs a leaf of a thread to run, which is a problem for ongoing threads. I also have a version the can start from the root or mid thread and continue to the last published leaf. Is it worth making the threading to be able to traverse in either direction?

**Comment by llrs** [comment]
This PR might close #164. I think it makes sense to look up and down.

**Comment by llrs** [comment]
Thanks @yonicd finally it can be merged

**Comment by yonicd** [comment]
i totally forgot about this PR (2 yrs is a long time :) ). 

thanks for merging it!

**Pull request merged**
