### PR TITLE
More token clean up

### LINKED ISSUE #438: rtweet authentication not working for script running as a local job
### Problem

I have an R script that fetches the friends of a user. It reads the API consumer keys and access keys and secrets from an RData file, creates a new token, and then uses this token to fetch the friends of a user. When I run this script normally (for example, by clicking "source" on RStudio) it runs just fine. However, when I do "Source as Local Job" it doesn't work, giving an authentication error.

### Expected behavior

I expect the authentication to happen even when the script is running as a local job (in the background)

### Reproduce the problem

``` r
library(rtweet)

load("../tokens/twitter_tokens/token1.Rdata")

tk <- create_token(
  app = token_name,
  consumer_key = api_key,
  consumer_secret = api_secret_key,
  access_token = access_token_key,
  access_secret = access_token_secret
)

users <- c("cnn", "bbc")

for(u in users) {
  u_data <- lookup_users(u)
  u_friends <- get_friends(
    u,
    n = u_data$friends_count,
    retryonratelimit = TRUE,
    token = tk
  )
  
  save(u_friends, file = paste0("../friends/", u, ".Rdata"))
  
}

```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")

[1] ‘0.7.0’
```

### Session info

``` r
## copy/paste output
sessionInfo()

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.0   stringr_1.4.0   dplyr_1.0.1     purrr_0.3.4     readr_1.3.1     tidyr_1.1.1     tibble_3.0.3   
 [8] ggplot2_3.3.2   tidyverse_1.3.0 rtweet_0.7.0   

loaded via a namespace (and not attached):
 [1] tinytex_0.25     tidyselect_1.1.0 xfun_0.16        haven_2.3.1      colorspace_1.4-1 vctrs_0.3.2     
 [7] generics_0.0.2   blob_1.2.1       rlang_0.4.7      later_1.1.0.1    pillar_1.4.6     withr_2.2.0     
[13] glue_1.4.1       DBI_1.1.0        dbplyr_1.4.4     modelr_0.1.8     readxl_1.3.1     lifecycle_0.2.0 
[19] munsell_0.5.0    gtable_0.3.0     cellranger_1.1.0 rvest_0.3.6      httpuv_1.5.4     curl_4.3        
[25] fansi_0.4.1      broom_0.7.0      Rcpp_1.0.5       openssl_1.4.2    promises_1.1.1   backports_1.1.7 
[31] scales_1.1.1     jsonlite_1.7.0   fs_1.5.0         askpass_1.1      hms_0.5.3        stringi_1.4.6   
[37] grid_4.0.2       cli_2.0.2        tools_4.0.2      magrittr_1.5     crayon_1.3.4     pkgconfig_2.0.3 
[43] ellipsis_0.3.1   xml2_1.3.2       reprex_0.3.0     lubridate_1.7.9  assertthat_0.2.1 httr_1.4.2      
[49] rstudioapi_0.11  R6_2.4.1         compiler_4.0.2  

```

### Token

``` r
## copy/paste output
rtweet::get_token()

<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> rsta******************
  key:    6j7I**********************************
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret, user_id, screen_name

```

### PR DESCRIPTION
**Pull request by hadley**
* Deprecate set_renv in favour of cache
* Default cache to FALSE
* Export token_cache_path()
* Import deprecated to match recommended style

Fixes #438

### CODE REVIEW

**Comment by llrs** [comment]
- Deprecate set_renv in favour of cache: OK
- Default cache to FALSE: Why? This would be another breaking change for users. 
- Export token_cache_path(): OK
- Import deprecated to match recommended style: Which style do you refer to? There isn't any style set for this package.
- Not sure I understand how these changes fix #438. Wouldn't the token generated with create_token would already be cached and used as default for subsequent calls (without this PR)?

**Comment by hadley** [comment]
I think having `create_token()` overwrite a file on disk by default is extremely surprising; creating a token in one app, should not (by default) affect every other app. Yes, I think overhauling auth is going to break existing code, but in conjunction with #469, I think it's very much worth it.

Standard deprecation style is documented at https://lifecycle.r-lib.org/articles/communicate.html#deprecating-an-argument-providing-a-new-default-1

Hmmm, yes, maybe this doesn't fix 438, except to reduce confusion over exactly what is happening when you create a token. 

For question that directly related to code, do you mind asking them comments in the PR? That makes it easier to follow the individual threads of discussion.

**Comment by hadley** [comment]
Also might be better to just close this and #530, and attack in a single PR that addresses #469.

**Comment by hadley** [comment]
Closing since I'm now pretty sure this isn't going to be useful once we've fully considered auth.

**Pull request closed without merging**
