### PR TITLE
Rely on standard create_token() logic in tests

### PR DESCRIPTION
**Pull request by hadley**
This gets most of the tests passing locally for me. A few failed because (I think) they require tweets accessible only from kearneymw's account; I explicitly skipped those.

The next step would be to get `create_token()` working on GHA. I don't know enough about twitter's auth options to offer any concrete advice here, but I'm happy to offer suggestions.

### CODE REVIEW

**Comment by hadley** [comment]
I also excised the use of `set_renv()` in the tests — modifying my `~/.Renviron` is extremely surprising.

**Comment by hadley** [comment]
Oh it looks like you could use https://docs.ropensci.org/rtweet/articles/auth.html#2-access-token-secret-method — you'd put those api_key, api_secret_key, access_token, access_token_secret in the repository secrets, and then modify the github action to expose them through the appropriate env vars.

**Comment by llrs** [comment]
Thanks! Yes, I was aware of how GHA handles secrets as I got to know both rtweet and GHA secrets more when creating a twitter bot. 
Will continue with this another day but when I tested your PR  on my computer I don't get many PASS:
[ FAIL 10 | WARN 3 | SKIP 0 | PASS 9 ]
And it asked for username on twitter and added it to ~/.Renviron adding it (when running it from the R terminal).

**Comment by hadley** [comment]
Hmmm, weird. I don't think I have anything special configured for rtweet auth. Can you share some of the failures you're seeing? I get:

```
[ FAIL 0 | WARN 0 | SKIP 4 | PASS 187 ]
```

**Comment by llrs** [comment]
Here is the report I get on your PR (using R 3.6.3).
Did you check if you have a twitter_tokens saved on the project or tests directory? (Aside from modifying the .Renviron the test_aaa saved the token for later usage, so it might still be there)

```
==> devtools::test()

Loading rtweet
Testing rtweet
✓ |  OK F W S | Context
x |   0 1 1   | test-access-level [0.5 s]                                                                          
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test_access_level.R:6:3): api_access_level works
Your credentials do not allow access to this resource - 220
Backtrace:
 1. rtweet::api_access_level() test_access_level.R:6:2
 2. rtweet::warn_for_twitter_status(r) /home/lrevilla/Documents/projects/rtweet/R/access_level.R:5:2

Failure (test_access_level.R:7:3): api_access_level works
is.character(a) && length(a) == 1 is not TRUE

`actual`:   FALSE
`expected`: TRUE 
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ |   2       | bearer_token [2.1 s]                                                                               
x |   2 1 1   | lookup_collections [0.2 s]                                                                         
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test_collections.R:7:3): lookup_collections returns tweets data
Your credentials do not allow access to this resource - 220
Backtrace:
 1. rtweet::lookup_collections("custom-539487832448843776") test_collections.R:7:2
 2. rtweet::warn_for_twitter_status(r) /home/lrevilla/Documents/projects/rtweet/R/collections.R:49:2

Failure (test_collections.R:10:3): lookup_collections returns tweets data
all(c("response", "objects") %in% names(x)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
x |   0 1 1   | direct_messages [0.2 s]                                                                            
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test_direct_messages.R:6:3): direct_messages functions
Your credentials do not allow access to this resource - 220
Backtrace:
 1. rtweet::direct_messages() test_direct_messages.R:6:2
 2. rtweet::is_read_write_directmessages(token) /home/lrevilla/Documents/projects/rtweet/R/direct_messages.R:51:2
 3. rtweet::api_access_level(token) /home/lrevilla/Documents/projects/rtweet/R/access_level.R:14:2
 4. rtweet::warn_for_twitter_status(r) /home/lrevilla/Documents/projects/rtweet/R/access_level.R:5:2

Error (test_direct_messages.R:6:3): direct_messages functions
Error: Token does not have `read-write-directmessages` access level. For DM permissions, users must create their own app at developer.twitter.com
Backtrace:
 1. rtweet::direct_messages() test_direct_messages.R:6:2
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
x |   4 2     | friendships [0.6 s]                                                                                
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (test_friendships.R:8:3): friendships returns data
is.data.frame(x) not equal to TRUE.
1 element mismatch

Failure (test_friendships.R:10:3): friendships returns data
"screen_name" %in% names(x) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
x |   1 1     | get_favorites [0.2 s]                                                                              
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test_get_favorites.R:7:3): get_favorites returns tweets data
Error: argument is of length zero
Backtrace:
  1. rtweet::get_favorites("kearneymw", n = n) test_get_favorites.R:7:2
  3. rtweet::get_favorites_call(...)
  4. base::Map(...) /home/lrevilla/Documents/projects/rtweet/R/favorites.R:109:4
  5. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
  8. rtweet::rate_limit.default(token, query) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:57:2
  9. rtweet::rate_limit_(token, query, parse) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:65:2
 10. rtweet::warn_for_twitter_status(r) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:152:2
 11. rtweet::from_js(x) /home/lrevilla/Documents/projects/rtweet/R/direct_messages.R:170:4
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
x |   0 1     | get_followers [0.2 s]                                                                              
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test_get_followers.R:6:3): get_followers returns data frame with user_id
Error: argument is of length zero
Backtrace:
 1. rtweet::rate_limit(NULL, "get_followers") test_get_followers.R:6:2
 2. rtweet::rate_limit.NULL(NULL, "get_followers") /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:57:2
 4. rtweet::rate_limit.default(token = token, query = query, parse = parse) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:57:2
 5. rtweet::rate_limit_(token, query, parse) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:65:2
 6. rtweet::warn_for_twitter_status(r) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:152:2
 7. rtweet::from_js(x) /home/lrevilla/Documents/projects/rtweet/R/direct_messages.R:170:4
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
x |   0 1     | get_friends [0.2 s]                                                                                
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test_get_friends.R:6:5): get_friends returns data frame with ids
Error: argument is of length zero
Backtrace:
 1. rtweet::rate_limit(NULL, "get_followers") test_get_friends.R:6:4
 2. rtweet::rate_limit.NULL(NULL, "get_followers") /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:57:2
 4. rtweet::rate_limit.default(token = token, query = query, parse = parse) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:57:2
 5. rtweet::rate_limit_(token, query, parse) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:65:2
 6. rtweet::warn_for_twitter_status(r) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:152:2
 7. rtweet::from_js(x) /home/lrevilla/Documents/projects/rtweet/R/direct_messages.R:170:4
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
x |   0 1     | get_my_timeline [0.2 s]                                                                            
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test_get_my_timeline.R:6:3): get_my_timeline
Error: cannot determine authenticating user.
To set manually, enter {screen_name} and append this to your .Renviron file:
TWITTER_SCREEN_NAME={screen_name} 
Backtrace:
 1. rtweet::get_my_timeline() test_get_my_timeline.R:6:2
 2. rtweet::home_user() /home/lrevilla/Documents/projects/rtweet/R/get-my-timeline.R:47:2
 5. rtweet::home_user_()
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ |   0 1     | get_timeline [0.2 s]                                                                               
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test_get_timelines.R:7:3): get_timeline
Error: argument is of length zero
Backtrace:
  1. rtweet::get_timeline(c("cnnbrk", "cnn"), n = n) test_get_timelines.R:7:2
  3. rtweet::get_timeline_(...)
  4. base::Map(...) /home/lrevilla/Documents/projects/rtweet/R/timeline.R:107:4
  5. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
  8. rtweet::rate_limit.default(token, query) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:57:2
  9. rtweet::rate_limit_(token, query, parse) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:65:2
 10. rtweet::warn_for_twitter_status(r) /home/lrevilla/Documents/projects/rtweet/R/rate_limit.R:152:2
 11. rtweet::from_js(x) /home/lrevilla/Documents/projects/rtweet/R/direct_messages.R:170:4
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Maximum number of failures exceeded; quitting early.
You can increase this number by setting `options(testthat.progress.max_fails)` 

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 4.5 s

[ FAIL 10 | WARN 3 | SKIP 0 | PASS 9 ]
══ Terminated early ═══════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by hadley** [comment]
Hmmm, I don't have either of those files and if I delete `~/.rtweet_token.1rds` and friends (which should not be created in my home directory), I get a different error:

```
Error (test_access_level.R:3:1): (code run outside of `test_that()`)
Error: API user token required. see http://rtweet.info/articles/auth.html for instructions
Backtrace:
 1. base::print(get_tokens()) test_access_level.R:3:0
 2. rtweet::get_tokens()
 3. rtweet::load_tokens(twitter_pat()) /Users/hadley/Desktop/rtweet/R/tokens.R:121:4
 4. base::Map("load_tokens_", pat = pat, MoreArgs = list(env = env)) /Users/hadley/Desktop/rtweet/R/tokens.R:429:2
 5. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
 7. rtweet::rtweet_token() /Users/hadley/Desktop/rtweet/R/tokens.R:452:4
 8. rtweet::rstats2twitter_client() /Users/hadley/Desktop/rtweet/R/tokens.R:535:4
```

**Comment by hadley** [comment]
Looking at the auth flow, I'd suggest rewriting it from scratch, accepting that the next package release will require all users to re-auth (which isn't that hard). I think it currently looks in too many places and writes too many files in places that it shouldn't — that substantially increases the risk of accidentally exposing your credentials to the world.

**Comment by llrs** [comment]
Thanks for the suggestion. Will take the chance to use rappdirs to store them.

**Comment by hadley** [comment]
I'm happy to do that if you want. I already started simplifying some of the token creation code.

**Comment by llrs** [comment]
Yeah, that would be great, I don't have much experiences with OAuth (and can't keep up with your speed). 
However, I would like to help users move to OAuth silently or not.

**Comment by hadley** [comment]
@llrs do you have access to account that hosts the rstats2twitter app?

**Comment by llrs** [comment]
No, that's why I wanted to contact Twitter to see what could be done. I already created another account for rtweet in case it is needed I only need to ask for developer access.

**Comment by hadley** [comment]
@llrs I very much doubt that twitter will be able to do anything, fortunately I don't think there's any problem with changing dev accounts. I'd suggest creating a new twitter account specifically for this account, and working with ROpenSci folks to ensure that they have some way to log into that account too.

**Comment by hadley** [comment]
@llrs I've plumbed it together so that you should just be able to set RTWEET_ACCESS_TOKEN and RTWEET_ACCESS_SECRET env vars using GitHub secrets, and the auth should just work. The chances of me doing this correctly on first go are low, so we'll probably have to iterate a little to get all the details right.

**Comment by llrs** [comment]
Many changes! Thanks! Now I get:
● Auth not available (29)
● requires kearneymw as twitter auth (4)

[ FAIL 0 | WARN 0 | SKIP 33 | PASS 19 ]

Reading the diffs I have some comments/questions:

You use rappdirs::user_cache_dir, in token_cache_path; shouldn't that be rappdirs::user_config_dir? Not sure which path is better, to me it looks like config is a better fit. 
Some users (including me) manage several accounts and thus apps and tokens. I will expand `get_tokens` to list and select which token to use. 

Also I don't understand the  home_user function. Why is written this way? To hide the functionality away from the users or to evaluate on a the current environment? 

```r
home_user <- function() {
  eval(call("home_user_"))
}
```

The the table about which functionality can be done with each authentication was eliminated from the README. I think it would be a great selling point for users to get their own app, on the auth vignette. Probably I will need to extend/redo the table but I don't want to miss it. 

But still I need to review and understand better all these changes and test how it works.

**Comment by hadley** [comment]
* `rappdirs::user_cache_dir()` is definitely the right place; we're caching the auth token, not storing configuration.
* I'd recommend leaving multiple apps/users to another PR; this is already getting complex. I'd suggest starting with an issue to collect requirements.
* I just moved `home_user()` to its own file without changing the code; I don't think this function is actually needed at all but will require some significant refactoring before it can be removed.
* I left the important parts of the table in the text — I don't think you need to oversell creating your own app because it's quite complex and most people will not need it.

**Comment by llrs** [comment]
- To me it seemed like configuration, otherwise rtweet doesn't work, but it doesn't really matter. 
- Indeed, it was so that you would be aware. Not to further extend this PR. 
- Now that I reread the changes I understood that move. Will try to remove home_user, specially since it has been promoted in the examples even if it is an internal function.
- Let's see what @sckott says about keeping the table comparing authentication methods. 

I pushed some minor changes on the vignette. But I would merge this as is.

**Comment by hadley** [comment]
@llrs Cool, just wanted to make sure we were on the same page. I'm happy to provide suggestions or review PRs when you work to add multi-app/user caching back in.

FWIW I think removing `home_user()` will be much easier after `TWIT` and friends are refactored (#483).

**Comment by llrs** [comment]
Great @hadley many thanks! I couldn't wish for a better reviewer. Will let you know when I get to it. 

Yes, I am seeing all the different ways the API is called: in the same function post_tweet there are calls to TWIT, or directly to httr::POST. Unifying all these calls provide some checks and logic will make a big difference.

**Comment by sckott** [comment]
@llrs the paragraph added does include the details of what the table used to have - i think it's sufficient

**Pull request merged**
