### PR TITLE
fix YAML

### PR DESCRIPTION
**Pull request by maelle**
@llrs is this the intended structure?

screenshot of the reference index produced by this PR

### CODE REVIEW

**Comment by llrs** [comment]
Yes, many thanks! I thought there would be more difference between titles and subtitles but a description to each title and subtitle  might help on this.

**Comment by maelle** [comment]
That might be a problem solved when rotemplate switches to BS5 :thinking:

**Comment by llrs** [comment]
I'm guessing that BS5 is the theme used. It might be just my preference/opinion not sure if it needs a change or it is simply that I'm  more familiar with the spacing on [ggplot2](https://ggplot2.tidyverse.org/reference/index.html) which has images that space the functions.

**Comment by maelle** [comment]
No, rotemplate doesn't use BS5 yet but it will soon.

Right, adding small icons could help too. :-)

**Pull request merged**
